_wandb:
    value:
        bounding_box/class_labels:
            Bounding Box Debugger/Images_wandb_delimeter_predictions:
                key: Bounding Box Debugger/Images_wandb_delimeter_predictions
                type: bounding_box/class_labels
                value:
                    "0": crack
                    "1": pillar
                    "2": spalling
        cli_version: 0.18.7
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 12
                - 41
                - 49
                - 55
                - 105
            "2":
                - 1
                - 2
                - 3
                - 12
                - 41
                - 49
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 19
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
adam:
    value: false
artifact_alias:
    value: latest
batch_size:
    value: 16
bbox_interval:
    value: -1
bucket:
    value: ""
cache_images:
    value: false
cfg:
    value: cfg/training/yolov7.yaml
data:
    value: /content/gdrive/MyDrive/yolov7/strukturpilar-2/data.yaml
data_dict:
    value:
        names:
            - crack
            - pillar
            - spalling
        nc: 3
        roboflow:
            license: MIT
            project: strukturpilar
            url: https://universe.roboflow.com/yolov7superstructuretest/strukturpilar/dataset/2
            version: 2
            workspace: yolov7superstructuretest
        test: ../test/images
        train: strukturpilar-2/train/images
        val: strukturpilar-2/valid/images
device:
    value: "0"
entity:
    value: null
epochs:
    value: 55
evolve:
    value: false
exist_ok:
    value: false
freeze:
    value:
        - 0
global_rank:
    value: -1
hyp:
    value:
        anchor_t: 4
        box: 0.05
        cls: 0.3
        cls_pw: 1
        copy_paste: 0
        degrees: 0
        fl_gamma: 0
        fliplr: 0.5
        flipud: 0
        hsv_h: 0.015
        hsv_s: 0.7
        hsv_v: 0.4
        iou_t: 0.2
        loss_ota: 1
        lr0: 0.01
        lrf: 0.1
        mixup: 0.15
        momentum: 0.937
        mosaic: 1
        obj: 0.7
        obj_pw: 1
        paste_in: 0.15
        perspective: 0
        scale: 0.9
        shear: 0
        translate: 0.2
        warmup_bias_lr: 0.1
        warmup_epochs: 3
        warmup_momentum: 0.8
        weight_decay: 0.0005
image_weights:
    value: false
img_size:
    value:
        - 640
        - 640
label_smoothing:
    value: 0
linear_lr:
    value: false
local_rank:
    value: -1
multi_scale:
    value: false
name:
    value: exp
noautoanchor:
    value: false
nosave:
    value: false
notest:
    value: false
opt:
    value:
        adam: false
        artifact_alias: latest
        batch_size: 16
        bbox_interval: -1
        bucket: ""
        cache_images: false
        cfg: cfg/training/yolov7.yaml
        data: /content/gdrive/MyDrive/yolov7/strukturpilar-2/data.yaml
        device: "0"
        entity: null
        epochs: 55
        evolve: false
        exist_ok: false
        freeze:
            - 0
        global_rank: -1
        hyp:
            anchor_t: 4
            box: 0.05
            cls: 0.3
            cls_pw: 1
            copy_paste: 0
            degrees: 0
            fl_gamma: 0
            fliplr: 0.5
            flipud: 0
            hsv_h: 0.015
            hsv_s: 0.7
            hsv_v: 0.4
            iou_t: 0.2
            loss_ota: 1
            lr0: 0.01
            lrf: 0.1
            mixup: 0.15
            momentum: 0.937
            mosaic: 1
            obj: 0.7
            obj_pw: 1
            paste_in: 0.15
            perspective: 0
            scale: 0.9
            shear: 0
            translate: 0.2
            warmup_bias_lr: 0.1
            warmup_epochs: 3
            warmup_momentum: 0.8
            weight_decay: 0.0005
        image_weights: false
        img_size:
            - 640
            - 640
        label_smoothing: 0
        linear_lr: false
        local_rank: -1
        multi_scale: false
        name: exp
        noautoanchor: false
        nosave: false
        notest: false
        project: runs/train
        quad: false
        rect: false
        resume: false
        save_dir: runs/train/exp4
        save_period: -1
        single_cls: false
        sync_bn: false
        total_batch_size: 16
        upload_dataset: false
        weights: yolov7.pt
        workers: 8
        world_size: 1
project:
    value: runs/train
quad:
    value: false
rect:
    value: false
resume:
    value: false
save_dir:
    value: runs/train/exp4
save_period:
    value: -1
single_cls:
    value: false
sync_bn:
    value: false
total_batch_size:
    value: 16
upload_dataset:
    value: false
weights:
    value: yolov7.pt
workers:
    value: 8
world_size:
    value: 1
